create table if not exists public.weekly_hero_selections (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  week_start timestamptz not null,
  status text not null default 'skipped' check (status in ('skipped','selected')),
  hero_ids integer[] not null default '{}',
  selected_at timestamptz,
  skipped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, week_start),
  constraint weekly_hero_selection_count check (
    (status = 'skipped' and cardinality(hero_ids) = 0 and selected_at is null)
    or
    (status = 'selected' and cardinality(hero_ids) = 4 and selected_at is not null)
  )
);

create index if not exists weekly_hero_selections_player_week_idx
  on public.weekly_hero_selections(player_id, week_start);

alter table public.weekly_hero_selections enable row level security;

grant all privileges on table public.weekly_hero_selections to service_role;
grant usage, select on all sequences in schema public to service_role;

-- The site reads/writes this table only through server-side API routes using service_role.
-- No public/anon policy is required.
